
#import "./typst-template.typ": Article

#let tabelaInfraestruturaBasica = (
  (
    indicador: "Água potável",
    percentualBrancaFmt: "99,5%",
    percentualPretaFmt: "99,7%",
    percentualPardaFmt: "99,5%",
    percentualAmarelaFmt: "99,5%",
    percentualIndigenaFmt: "99,5%",
    percentualNaoDeclaradaFmt: "99,8%",
    percentualQuilombolaFmt: "100,0%",
  ),
  (
    indicador: "Energia elétrica",
    percentualBrancaFmt: "100,0%",
    percentualPretaFmt: "100,0%",
    percentualPardaFmt: "100,0%",
    percentualAmarelaFmt: "100,0%",
    percentualIndigenaFmt: "100,0%",
    percentualNaoDeclaradaFmt: "100,0%",
    percentualQuilombolaFmt: "100,0%",
  ),
  (
    indicador: "Esgotamento sanitário",
    percentualBrancaFmt: "100,0%",
    percentualPretaFmt: "100,0%",
    percentualPardaFmt: "100,0%",
    percentualAmarelaFmt: "100,0%",
    percentualIndigenaFmt: "100,0%",
    percentualNaoDeclaradaFmt: "100,0%",
    percentualQuilombolaFmt: "100,0%",
  ),
  (
    indicador: "Biblioteca ou sala de leitura",
    percentualBrancaFmt: "55,5%",
    percentualPretaFmt: "56,7%",
    percentualPardaFmt: "57,2%",
    percentualAmarelaFmt: "56,6%",
    percentualIndigenaFmt: "52,1%",
    percentualNaoDeclaradaFmt: "60,0%",
    percentualQuilombolaFmt: "83,3%",
  ),
  (
    indicador: "Internet para alunos",
    percentualBrancaFmt: "34,0%",
    percentualPretaFmt: "35,7%",
    percentualPardaFmt: "35,3%",
    percentualAmarelaFmt: "34,5%",
    percentualIndigenaFmt: "35,9%",
    percentualNaoDeclaradaFmt: "33,1%",
    percentualQuilombolaFmt: "83,3%",
  ),
  (
    indicador: "Sala de professores",
    percentualBrancaFmt: "80,7%",
    percentualPretaFmt: "79,2%",
    percentualPardaFmt: "80,5%",
    percentualAmarelaFmt: "77,9%",
    percentualIndigenaFmt: "75,6%",
    percentualNaoDeclaradaFmt: "81,8%",
    percentualQuilombolaFmt: "83,3%",
  ),
  (
    indicador: "Banheiro",
    percentualBrancaFmt: "100,0%",
    percentualPretaFmt: "100,0%",
    percentualPardaFmt: "100,0%",
    percentualAmarelaFmt: "100,0%",
    percentualIndigenaFmt: "100,0%",
    percentualNaoDeclaradaFmt: "100,0%",
    percentualQuilombolaFmt: "100,0%",
  ),
  (
    indicador: "Todos os requisitos",
    percentualBrancaFmt: "18,6%",
    percentualPretaFmt: "19,3%",
    percentualPardaFmt: "19,6%",
    percentualAmarelaFmt: "21,5%",
    percentualIndigenaFmt: "15,3%",
    percentualNaoDeclaradaFmt: "19,4%",
    percentualQuilombolaFmt: "83,3%",
  ),
)

#Article(
  title: "AQUI TEM MEC - Devolutivas de Equidade Racial",
  municipio: "São Francisco do Sul",
  uf: "SC",

  // P2 - Complementação VAAR 
  p2PibPerCapita: "R$ 35.001,00",
  p2PibPerCapitaAno: "2021",
  p2NumeroHabitantes: "17.232",
  p2NumeroHabitantesAno: "2022",
  p2AnoReferencia: "2026",
  p2ValorComplementacaoVAARAnoReferencia: "0.0",
  p2ValorComplementacaoVAARMediaUF: "R$ 58.156.033,12",  
  p2ValorComplementacaoVAARMediaUFAno: "2025",
  condAnoReferencia: "2025",
  percentualCumprimentoCondicionalidade1Brasil: 99,
  percentualCumprimentoCondicionalidade2Brasil: 98,
  percentualCumprimentoCondicionalidade3Brasil: 66,
  percentualCumprimentoCondicionalidade4Brasil: 93,
  percentualCumprimentoCondicionalidade5Brasil: 90,
  percentualCumprimentoCondicionalidade1UF: 98,
  percentualCumprimentoCondicionalidade2UF: 0,
  percentualCumprimentoCondicionalidade3UF: 35,
  percentualCumprimentoCondicionalidade4UF: 90,
  percentualCumprimentoCondicionalidade5UF: 86,
  tabelaInfraestruturaBasica: tabelaInfraestruturaBasica,
  p2PortariaReferencia: "X",
  chartVaarMunicipio: "assets/charts/P1-G1.svg",
  chartCondicionalidadesBrasil: "assets/charts/P1-G2.svg",
  chartCondicionalidadesUf: "assets/charts/P1-G3.svg",
  condSelecaoDiretor: true,
  condParticipacaoSaeb: true,
  condReducaoDesigualdades: false,
  condRegulamentacaoIcms: true,
  condReferenciaisBncc: false,
  condAvancoAtendimento: true,
  condAvancoAprendizagem: true,
  populacaoQuilombola: "232",
  comunidadesQuilombolas: "32",
  populacaoQuilombolaAno: "2022",
  comunidadesQuilombolasAno: "2022",

  // P3 - Condicionalidade III
  p3PercentualRacial2019: "36,36%",
  p3PercentualRacial2023: "32,32%",
  p3DiferencaPercentualRacial: "4,24%",
  p3PercentualSocioeconomica2019: "41,41%",
  p3PercentualSocioeconomica2023: "40,40%",
  p3DiferencaPercentualSocioeconomica: "1,10%",
  reduziuDesigualdadeRacial: "Não reduziu a desigualdade racial",
  margemDeErroDesigualdadeRacial: "Sim",
  reduziuDesigualdadeSocioeconomica: "Reduziu a desigualdade socioeconômica",  
  margemDeErroDesigualdadeSocioeconomica: "Sim",
  habilitadoCondicionalidade: "Sim",
  habilitadoCondicionalidadeMotivo: "Habilitado porque apresentou IDPPI_aj ajustado e IDNSE_aj ajustado iguais a zero (incluído na margem de erro)",
  p3AnoReferencia: "2025",
  chartAlunosAprendizagemAdequada: "assets/charts/P3-G1.svg",
  chartAlunosBaixoNSE: "assets/charts/P3-G2.svg",

  // P4 - Diagnóstico 1
  chartAtendimentoCrechePreEscola: "assets/charts/P4-G1.svg",
  chartDistribuicaoMatriculas: "assets/charts/P4-G2.svg",
  chartDeclaracaoRacial: "assets/charts/P4-G3.svg",

  // P5 - Diagnóstico 2
  chartNivelFormacaoProfessores: "assets/charts/P5-G1.svg",
  chartTaxaRendimento: "assets/charts/P5-G3.svg",

  // P6 - Diagnóstico 3
  mediaIndiceGeralERERMunicipal: "19,0",
  minimoIndiceGeralERERMunicipal: "XX,X",
  maximoIndiceGeralERERMunicipal: "XX,X",
  medianaIndiceGeralERERMunicipal: "XX,X",
  mediaIndiceGeralERERUF: "XX,X",
  minimoIndiceGeralERERUF: "XX,X",
  maximoIndiceGeralERERUF: "XX,X",
  // Essse percentual é obtido pela seguinte fórmula:
  // (media-minimo)/(maximo-minimo)
  percentualIndiceGeralERERMunicipal: "15",
  percentualIndiceGeralERERUF: "15",
  mediaIndiceGeralERERBrasil: "XX,X",
  minimoIndiceGeralERERBrasil: "XX,X",
  maximoIndiceGeralERERBrasil: "XX,X",
  medianaIndiceGeralERERBrasil: "XX,X",
  percentualIndiceGeralERERBrasil: "15",
  formacoesERER: 10,
  revisaoCurriculo: "Precisa avançar",
  aquisicaoMateriais: "Não realizou",
  adocaoCriterioPriorizacao: "Não realizou",
  // Índices ERER
  indiceERER1Media: "20,0",
  indiceERER1Minimo: "0,1",
  indiceERER1Maximo: "99,9",
  indiceERER1Mediana: "21,4",
  indiceERER2Media: "20,0",
  indiceERER2Minimo: "2,0",
  indiceERER2Maximo: "99,9",
  indiceERER2Mediana: "21,4",
  indiceERER3Media: "20,0",
  indiceERER3Minimo: "0,0",
  indiceERER3Maximo: "99,9",
  indiceERER3Mediana: "21,4",
  indiceERER4Media: "20,0",
  indiceERER4Minimo: "0,0",
  indiceERER4Maximo: "99,9",
  indiceERER4Mediana: "21,4",
  indiceERER5Media: "20,0",
  indiceERER5Minimo: "0,0",
  indiceERER5Maximo: "99,9",
  indiceERER5Mediana: "21,4",
  indiceERER6Media: "20,0",
  indiceERER6Minimo: "0,0",
  indiceERER6Maximo: "99,9",
  indiceERER6Mediana: "21,4",
  indiceERER7Media: "20,0",
  indiceERER7Minimo: "0,0",
  indiceERER7Maximo: "99,9",
  indiceERER7Mediana: "21,4",
  // Índices EEQ
  indiceEEQ1Municipio: "20,3",
  indiceEEQ1MediaUF: "0,0",
  indiceEEQ1MediaBrasil: "99,9",
  statusRespostaEEQ: "21,4",
  indiceEEQ2Municipio: "20,0",
  indiceEEQ2MediaUF: "0,0",
  indiceEEQ2MediaBrasil: "99,9",
  indiceEEQ3Municipio: "20,0",
  indiceEEQ3MediaUF: "0,0",
  indiceEEQ3MediaBrasil: "99,9",
  indiceEEQ4Municipio: "20,0",
  indiceEEQ4MediaUF: "0,0",
  indiceEEQ4MediaBrasil: "99,9",

  
)[
  // Adicionar futuro conteúdo aqui
]
